services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
    plan: free